modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/demistorm/VR-Swing-Sprint/issues"
license = "GPL-3.0"

[[mods]]
modId = "vr_swing_sprint"
version = "${version}"
displayName = "VR Swing Sprint"
displayURL = "https://github.com/demistorm/VR-Swing-Sprint"
logoFile = "vss-logo.png"
authors = "Halfstorm"
description = '''
Mod that allows Vivecraft players to run by swinging their arms like Blade and Sorcery!

Support me on Ko-Fi: https://ko-fi.com/hstorm

Discord: https://discord.gg/7uttzPbTGq

Requires Vivecraft mod.
'''

[[mixins]]
config = "vss.mixins.json"

[[dependencies.vr_swing_sprint]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_swing_sprint]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_swing_sprint]]
modId = "vivecraft"
mandatory = true
versionRange = "[1.3.3,)"
ordering = "AFTER"
side = "BOTH"
