modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/demistorm/VR-Swing-Sprint/issues"
license = "GPL-3.0"

[[mods]]
modId = "vr_swing_sprint"
version = "${version}"
displayName = "VR Swing Sprint"
displayURL = "https://github.com/demistorm/VR-Swing-Sprint"
authors = "Halfstorm"
description = '''
Mod that allows Vivecraft players to run by swinging their arms like Blade and Sorcery!

Requires Vivecraft mod.
'''

[[dependencies.vr_swing_sprint]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_swing_sprint]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_swing_sprint]]
modId = "vivecraft"
mandatory = true
versionRange = "[1.3.3,)"
ordering = "AFTER"
side = "BOTH"
